"""Windows Task Scheduler 常驻单元生成（site-delivery Task 8 / M2）。

mac 生产档 = launchd plist（com.bokvoice.<unit>，RunAtLoad + KeepAlive）；
Windows 对应物 = Task Scheduler 任务（任务名约定 bok-<unit>，一 unit 一 task）：
  BootTrigger                     ←→ RunAtLoad（开机自起，不依赖登录用户）
  RestartOnFailure(PT1M × Count3) ←→ KeepAlive（崩溃自动拉回）
  Principal S-1-5-18 (SYSTEM,
  RunLevel HighestAvailable)      ←→ 无头会话（SYSTEM 不占桌面、不需登录）

Task Scheduler XML 没有 env-var 元素（launchd 有 EnvironmentVariables dict）——
标准 workaround 是 env 前缀链：action 用 cmd.exe 包一层：

  cmd.exe /c cd /d "<ROOT>" && set "K=V" && set "K2=V2" && "exe" args >> out.log 2>> err.log

  - 首元素固定 cd /d：复刻 plist WorkingDirectory，同时保证 /c 后首个字符不是
    引号——cmd /c 对「首字符为引号」的命令行走剥首尾引号老规则，链条会被拆坏；
  - set "K=V" 逐个注入；env dict 与 mac plists 完全同源（bok.py cmd_prod_install
    单点组装，含 _bake_ssl_cert_file 产物）；
  - >> / 2>> 双文件重定向复刻 StandardOutPath / StandardErrorPath（app-data/logs）。
cmd 语法限制：set "K=V" 的值不能含双引号（env 值都是路径/URL，成立）；值含 "&"
会截断链条（路径不含 &，成立）——异常 env 值在 install 时原样落链，属运维责任面。

本模块纯函数本位：只生成 XML 字符串 / argv 列表 / utf-16 落盘；唯一副作用出口
run_schtasks() / apply_firewall_rules()，只被 bok.py prod 在 Windows 实机调用。
生命周期实跑量尺：scripts/probe_windows_lifecycle.py B 段（M4 windows-latest CI）。
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path
from xml.sax.saxutils import escape as _xml_escape

# 任务名约定 bok-<unit>；URI 收口 \BokVoice\<unit>（一 unit 一 task）。
TASK_NAME_PREFIX = "bok"
TASK_URI_ROOT = "\\BokVoice"

# 防火墙放行面：control-plane(:8000) 与 LiveKit 信令/媒体(:7880)，TCP+UDP 各一条。
FIREWALL_PORTS = (8000, 7880)
FIREWALL_PROTOCOLS = ("TCP", "UDP")
FIREWALL_NAME_PREFIX = "Bok Voice"


def task_name(unit: str) -> str:
    """任务名 bok-<unit>。unit 已带 bok- 前缀（mac plist 同名单元，如 bok-agent）
    时原样收口，避免 bok-bok-agent 双前缀。"""
    prefix = TASK_NAME_PREFIX + "-"
    base = unit[len(prefix):] if unit.startswith(prefix) else unit
    return TASK_NAME_PREFIX + "-" + base


def task_uri(unit: str) -> str:
    return f"{TASK_URI_ROOT}\\{task_name(unit)}"


def build_unit_task_xml(unit: str, command: str, arguments: str,
                        working_dir: str = "", description: str = "") -> str:
    """生成单个 unit 的 Task Scheduler 任务 XML（纯函数）。

    元素顺序必须按 Task Scheduler schema（RegistrationInfo → Triggers →
    Principals → Settings → Actions），乱序 schtasks /create 直接拒。
    落盘必须走 write_task_xml()（/xml 只认带 BOM 的 UTF-16）。"""
    uri = task_uri(unit)
    desc = description or (
        f"Bok Voice stack unit: {task_name(unit)} "
        "(onstart + RestartOnFailure, SYSTEM). Generated by tools/schtasks_units.py")
    args_xml = (f"      <Arguments>{_xml_escape(arguments)}</Arguments>\n"
                if arguments else "")
    wd_xml = (f"      <WorkingDirectory>{_xml_escape(working_dir)}</WorkingDirectory>\n"
              if working_dir else "")
    return f"""<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Description>{_xml_escape(desc)}</Description>
    <URI>{_xml_escape(uri)}</URI>
  </RegistrationInfo>
  <Triggers>
    <BootTrigger>
      <Enabled>true</Enabled>
    </BootTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>S-1-5-18</UserId>
      <RunLevel>HighestAvailable</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>true</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>
    <Priority>7</Priority>
    <RestartOnFailure>
      <Interval>PT1M</Interval>
      <Count>3</Count>
    </RestartOnFailure>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>{_xml_escape(command)}</Command>
{args_xml}{wd_xml}    </Exec>
  </Actions>
</Task>
"""


def write_task_xml(path: Path, xml: str) -> Path:
    """XML 落盘。schtasks /xml 只认带 BOM 的 UTF-16（utf-8 落盘报 0x8007000D）。"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(xml, encoding="utf-16")
    return path


def _cmd_quote(arg: str) -> str:
    """含空白（或空）的参数加引号；普通 token 原样。"""
    if not arg or any(c.isspace() for c in arg):
        return f'"{arg}"'
    return arg


def build_cmd_arguments(env: dict[str, str], command: list[str],
                        working_dir: str, log_stdout: str | Path,
                        log_stderr: str | Path) -> str:
    """cmd.exe 的 /c 参数串：env 前缀链 + 命令 + 双文件重定向（见模块 docstring）。"""
    if not command:
        raise ValueError("command must be non-empty")
    exe, *rest = command
    cmdline = " ".join([f'"{exe}"', *(_cmd_quote(a) for a in rest)])
    redirects = f'>> "{log_stdout}" 2>> "{log_stderr}"'
    chain = [f'cd /d "{working_dir}"']
    chain.extend(f'set "{k}={env[k]}"' for k in sorted(env))
    chain.append(f"{cmdline} {redirects}")
    return "/c " + " && ".join(chain)


# ---- schtasks 生命周期（create / query / run / end / delete）argv 组装 ----


def schtasks_create_argv(tname: str, xml_file: str | Path) -> list[str]:
    return ["schtasks", "/create", "/tn", tname, "/xml", str(xml_file), "/f"]


def schtasks_query_argv(tname: str) -> list[str]:
    return ["schtasks", "/query", "/tn", tname]


def schtasks_end_argv(tname: str) -> list[str]:
    return ["schtasks", "/end", "/tn", tname]


def schtasks_delete_argv(tname: str) -> list[str]:
    return ["schtasks", "/delete", "/tn", tname, "/f"]


def run_schtasks(argv: list[str], timeout: float = 60.0) -> subprocess.CompletedProcess:
    return subprocess.run(argv, capture_output=True, text=True, timeout=timeout)


# ---- 防火墙放行（netsh advfirewall；默认 print-only，--open-firewall 才执行）----


def firewall_rule_argv(port: int, protocol: str,
                       name_prefix: str = FIREWALL_NAME_PREFIX) -> list[str]:
    """单条入站放行规则 argv。name 值含空格——subprocess list 形式由 list2cmdline
    统一加引号（netsh 接受整 token 引号形式 name="Bok Voice 8000 TCP"）。"""
    return [
        "netsh", "advfirewall", "firewall", "add", "rule",
        f"name={name_prefix} {port} {protocol}",
        "dir=in", "action=allow", f"protocol={protocol}", f"localport={port}",
    ]


def firewall_rules_argv(ports: tuple[int, ...] = FIREWALL_PORTS,
                        protocols: tuple[str, ...] = FIREWALL_PROTOCOLS,
                        name_prefix: str = FIREWALL_NAME_PREFIX) -> list[list[str]]:
    return [firewall_rule_argv(p, proto, name_prefix)
            for p in ports for proto in protocols]


def _printable(argv: list[str]) -> str:
    return " ".join(_cmd_quote(a) for a in argv)


def apply_firewall_rules(execute: bool,
                         ports: tuple[int, ...] = FIREWALL_PORTS,
                         protocols: tuple[str, ...] = FIREWALL_PROTOCOLS,
                         name_prefix: str = FIREWALL_NAME_PREFIX,
                         run=None) -> int:
    """防火墙放行：默认只打印 netsh 计划（零副作用）；execute=True 才执行
    （需要管理员权限的 shell）。返回 0=全过 / 非 0=有失败（install 汇总用）。
    run 参数供测试注入，缺省 subprocess.run。"""
    runner = run if run is not None else subprocess.run
    rc = 0
    for argv in firewall_rules_argv(ports, protocols, name_prefix):
        if not execute:
            print(f"[firewall] (plan) {_printable(argv)}")
            continue
        print(f"[firewall] $ {_printable(argv)}")
        try:
            r = runner(argv, capture_output=True, text=True, timeout=60)
        except Exception as exc:  # noqa: BLE001 - 单条失败不拦其余规则
            print(f"[firewall] FAILED {' '.join(argv[1:])}: {exc!r}", file=sys.stderr)
            rc = rc or 1
            continue
        if r.returncode != 0:
            tail = ((r.stderr or "").strip() or (r.stdout or "").strip()).splitlines()
            detail = tail[-1][:200] if tail else ""
            print(f"[firewall] FAILED rc={r.returncode} {detail} "
                  "(需要管理员权限？)", file=sys.stderr)
            rc = rc or r.returncode
    if not execute:
        print("[firewall] plan-only；执行请 bok.py prod install --open-firewall"
              "（管理员 PowerShell）")
    return rc
